# Generated by Django 2.2.6 on 2020-05-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfb', '0003_auto_20200502_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica_equipo_partido',
            name='tasa_tapones',
            field=models.FloatField(default=0, verbose_name='TTap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadistica_jugador_partido',
            name='tasa_tapones',
            field=models.FloatField(default=0, verbose_name='TTAP'),
            preserve_default=False,
        ),
    ]
