# Generated by Django 2.2.6 on 2020-05-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfb', '0004_auto_20200502_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipos',
            options={'ordering': ['zona', 'nombre_corto']},
        ),
        migrations.AlterModelOptions(
            name='jugadores',
            options={'ordering': ['id_equipo']},
        ),
        migrations.AlterModelOptions(
            name='partidos',
            options={'ordering': ['detalle_partido']},
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='nombre',
            new_name='nombre_corto',
        ),
        migrations.AddField(
            model_name='equipos',
            name='nombre_largo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
