# Generated by Django 2.2.6 on 2020-05-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfb', '0006_auto_20200503_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='id_jugador',
            field=models.IntegerField(),
        ),
    ]
