# Generated by Django 2.2.6 on 2020-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfb', '0007_auto_20200505_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica_jugador_partido',
            name='inicial',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
