# Generated by Django 2.2.6 on 2020-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfb', '0009_auto_20200509_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='urlLogo',
            new_name='logoL',
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='urlIMG',
            new_name='photoL',
        ),
        migrations.AddField(
            model_name='equipos',
            name='logoS',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='photoS',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica_jugador_partido',
            name='inicial',
            field=models.IntegerField(),
        ),
    ]
