# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class PartidoItem(scrapy.Item):
    detalle_partido = scrapy.Field()
    fibalink        = scrapy.Field()

class JugadorItem(scrapy.Item):
    id_jugador  = scrapy.Field()
    nombre      = scrapy.Field()   
    equipo      = scrapy.Field()
    urlIMG      = scrapy.Field()

class StatsTeamItem(scrapy.Item):
    id_partido              = scrapy.Field()
    equipoA                 = scrapy.Field()
    equipoB                 = scrapy.Field()
    puntosA                 = scrapy.Field()
    puntosB                 = scrapy.Field()
    local                   = scrapy.Field()
    visitante               = scrapy.Field()
    tccA                    = scrapy.Field()
    tccB                    = scrapy.Field()
    tciA                    = scrapy.Field()
    tcpA                    = scrapy.Field()
    tcpB                    = scrapy.Field()
    t2cA                    = scrapy.Field()
    t2cB                    = scrapy.Field()
    t2iA                    = scrapy.Field()
    t2iB                    = scrapy.Field()
    t2pA                    = scrapy.Field()
    t2pB                    = scrapy.Field()
    t3cA                    = scrapy.Field()
    t3cB                    = scrapy.Field()
    tlcA                    = scrapy.Field()
    tlcB                    = scrapy.Field()
    tliA                    = scrapy.Field()
    tliB                    = scrapy.Field()
    roA                     = scrapy.Field()
    roB                     = scrapy.Field()
    rdA                     = scrapy.Field()
    rdB                     = scrapy.Field()
    rtA                     = scrapy.Field()
    rtB                     = scrapy.Field()
    asisA                   = scrapy.Field()
    asisB                   = scrapy.Field()
    perA                    = scrapy.Field()
    perB                    = scrapy.Field()
    recA                    = scrapy.Field()
    recB                    = scrapy.Field()
    tapA                    = scrapy.Field()
    tapB                    = scrapy.Field()
    fpA                     = scrapy.Field()
    fpB                     = scrapy.Field()
    valA                    = scrapy.Field()
    valB                    = scrapy.Field()
    puntos_bancaA           = scrapy.Field()
    puntos_bancaB           = scrapy.Field()
    puntos_contraataqueA    = scrapy.Field()
    puntos_contraataqueB    = scrapy.Field()
    puntos_de_perdidasA     = scrapy.Field()
    puntos_de_perdidasB     = scrapy.Field()
    puntos_roA              = scrapy.Field()
    puntos_roB              = scrapy.Field()
    puntos_pinturaA         = scrapy.Field()
    puntos_pinturaB         = scrapy.Field()

class StatsPlayerItem(scrapy.Item):
    id_partido              = scrapy.Field()
    id_jugador              = scrapy.Field()
    equipo                  = scrapy.Field()
    minutos                 = scrapy.Field()
    puntos                  = scrapy.Field()
    tiros_campo_convertidos = scrapy.Field()
    tiros_campo_intentados  = scrapy.Field()
    tiros_campo_porcentaje  = scrapy.Field()
    tiros_2_convertidos     = scrapy.Field()
    tiros_2_intentados      = scrapy.Field()
    tiros_2_porcentaje      = scrapy.Field()
    tiros_3_convertidos     = scrapy.Field()
    tiros_3_intentados      = scrapy.Field()
    tiros_3_porcentaje      = scrapy.Field()
    tiro_libre_convertido   = scrapy.Field()
    tiro_libre_intentado    = scrapy.Field()
    tiros_libre_porcentaje  = scrapy.Field()
    rebote_ofensivo         = scrapy.Field()
    rebote_defensivo        = scrapy.Field()
    rebote_total            = scrapy.Field()
    asistencias             = scrapy.Field()
    perdidas                = scrapy.Field()
    recuperos               = scrapy.Field()
    tapones                 = scrapy.Field()
    faltas_personales       = scrapy.Field()
    faltas_recibidas        = scrapy.Field()
    diferencia_puntos       = scrapy.Field()
    valoración              = scrapy.Field()      