# Generated by Django 2.2.6 on 2020-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='license_type',
            field=models.CharField(choices=[('B', 'BASIC'), ('P', 'PRO'), ('F', 'FULL')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('E', 'ENTRENADOR'), ('A', 'AGENTE'), ('J', 'JUGADOR'), ('P', 'PERIODISTA')], max_length=40),
        ),
    ]
