# Generated by Django 2.2.6 on 2020-04-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Equipo')),
                ('nombre', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=255)),
                ('urlLogo', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['zona', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Partido')),
                ('detalle_partido', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_jugador', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('urlIMG', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('LES', 'LESIONADO'), ('B', 'BAJA')], default='A', max_length=3)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfb.Equipos')),
            ],
            options={
                'ordering': ['id_jugador'],
            },
        ),
        migrations.CreateModel(
            name='Estadistica_Jugador_Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.FloatField(verbose_name='Pts')),
                ('minutos', models.DurationField()),
                ('tiros_campo_convertidos', models.FloatField(verbose_name='TCc')),
                ('tiros_campo_intentados', models.FloatField(verbose_name='TCi')),
                ('tiros_campo_porcentaje', models.FloatField(verbose_name='%TC')),
                ('tiros_2_convertidos', models.FloatField(verbose_name='2Pc')),
                ('tiros_2_intentados', models.FloatField(verbose_name='2Pi')),
                ('tiros_2_porcentaje', models.FloatField(verbose_name='%2P')),
                ('tiros_3_convertidos', models.FloatField(verbose_name='3Pc')),
                ('tiros_3_intentados', models.FloatField(verbose_name='3Pi')),
                ('tiros_3_porcentaje', models.FloatField(verbose_name='%3P')),
                ('tiro_libre_convertido', models.FloatField(verbose_name='TLc')),
                ('tiro_libre_intentado', models.FloatField(verbose_name='TLi')),
                ('tiros_libre_porcentaje', models.FloatField(verbose_name='%TL')),
                ('rebote_ofensivo', models.FloatField(verbose_name='RO')),
                ('rebote_defensivo', models.FloatField(verbose_name='RD')),
                ('rebote_total', models.FloatField(verbose_name='RT')),
                ('asistencias', models.FloatField(verbose_name='Asist')),
                ('perdidas', models.FloatField(verbose_name='Perd')),
                ('recuperos', models.FloatField(verbose_name='Rec')),
                ('tapones', models.FloatField(verbose_name='Tap')),
                ('faltas_personales', models.FloatField(verbose_name='FP')),
                ('diferencia_puntos', models.FloatField(verbose_name='+-Pt')),
                ('valoración', models.FloatField(verbose_name='VAL')),
                ('id_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfb.Jugadores')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfb.Partidos')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica_Equipo_Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localia', models.CharField(max_length=1, null=True)),
                ('puntos', models.FloatField(verbose_name='Pts')),
                ('tiros_campo_convertidos', models.FloatField(verbose_name='TCc')),
                ('tiros_campo_intentados', models.FloatField(verbose_name='TCi')),
                ('tiros_campo_porcentaje', models.FloatField(null=True, verbose_name='%TC')),
                ('tiros_2_convertidos', models.FloatField(verbose_name='2Pc')),
                ('tiros_2_intentados', models.FloatField(verbose_name='2Pi')),
                ('tiros_2_porcentaje', models.FloatField(null=True, verbose_name='%2P')),
                ('tiros_3_convertidos', models.FloatField(verbose_name='3Pc')),
                ('tiros_3_intentados', models.FloatField(verbose_name='3Pi')),
                ('tiros_3_porcentaje', models.FloatField(null=True, verbose_name='%3P')),
                ('tiro_libre_convertido', models.FloatField(verbose_name='TLc')),
                ('tiro_libre_intentado', models.FloatField(verbose_name='TLi')),
                ('tiros_libre_porcentaje', models.FloatField(null=True, verbose_name='%TL')),
                ('rebote_ofensivo', models.FloatField(verbose_name='RO')),
                ('rebote_defensivo', models.FloatField(verbose_name='RD')),
                ('rebote_total', models.FloatField(null=True, verbose_name='RT')),
                ('asistencias', models.FloatField(verbose_name='Asist')),
                ('perdidas', models.FloatField(verbose_name='Perd')),
                ('recuperos', models.FloatField(verbose_name='Rec')),
                ('tapones', models.FloatField(verbose_name='Tap')),
                ('faltas_personales', models.FloatField(verbose_name='FP')),
                ('valoración', models.FloatField(verbose_name='VAL')),
                ('pace', models.FloatField(verbose_name='Pace')),
                ('eficiencia_tiro_campo', models.FloatField(verbose_name='eFG')),
                ('true_shooting', models.FloatField(verbose_name='TS')),
                ('eficiencia_ofensiva', models.FloatField(verbose_name='effOf')),
                ('eficiencia_defensiva', models.FloatField(verbose_name='effDef')),
                ('tasa_rebote_ofensivo', models.FloatField(verbose_name='TRO')),
                ('tasa_rebote_defensivo', models.FloatField(verbose_name='TRD')),
                ('tasa_recuperos', models.FloatField(verbose_name='TRec')),
                ('tasa_asistencias', models.FloatField(verbose_name='TAs')),
                ('tasa_perdidas', models.FloatField(verbose_name='TPer')),
                ('oportunidad_tiro_libre', models.FloatField(verbose_name='OpTL')),
                ('puntos_de_perdidas', models.FloatField(verbose_name='PtsPer')),
                ('puntos_pintura', models.FloatField(verbose_name='PtsPintura')),
                ('puntos_contraataque', models.FloatField(verbose_name='PtsCAT')),
                ('puntos_banca', models.FloatField(verbose_name='PtsSup')),
                ('partido_ganado', models.IntegerField(verbose_name='Ganado-Perdido')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfb.Equipos')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfb.Partidos')),
            ],
        ),
    ]
